language: node_js
sudo: required
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
env:
  global:
  - secure: WQW73Q3KWAbNJuI7husElhwkWp7Wr/GIfphWul/9vhOu2/jiqmKQCoM+FH2SkcxtwPbAT/veQf1ywwkEdCH0OulvGHrjnahPqjS+FwlO+Zt5KeT3ykhhGH3C35zbdUV0ibMlkrsTypjQvezO/ZDUqYW6ZpSSQenRt8tVJjZrPkNZk6nyeFhwxWD1KqMeuFmx/lSesBYhwxYtssZX8H8YCFuuqXNSP1prhc4D4MjCnM6IF6wsM3FY7yYZcHMJdtGfChjjpxqgT10vYHtSRK+lVdURCUTFH4A/qKVhp69HcF92b9ZMgpfT0I7N4mWxSFaF8rzpOYcgiebk5HtGswRP7wXKuFCgT07A6OY+D6ZPQPvgCEEz5kVFfP4iCyeo2MeGSTSncJu3IDsSow2m43ufXMJ0sGHljxGpujCBu1rAluP9iBMOLEG4hPTaxl6da61d+gqQwJXY/ymuY1WUy39SoqQaCMzC1uHYYLivCcMASQo5rVeV019e08iSp94zL3rBB2ENhJQFOo+sesVZSoff/c/of00oWIuRhswQLfRTZu1nIMpj67VIFzhGUFwnqzD2bZSNhk4rzr0nI6rtTUWyJ4KX/t9DhsCgKsFBHcdqhyUDMv+ITOWhewq60LzmfA4HbVfvZqQuXVnr0p17u+dTfCRqQlF3Y/llRQ48L5tLEbE=
  - secure: OuFCSsUX3u3R+FytOAOJQj0kguGkyDTyAQCwWAfZ/+Oj6JPE5PqfY3Z9HK/RdkEtZ4n0cXgq1/9LynTsMJvB6LVti172TQEWJhrmKDIugcll9W6FZjj5jQIhEp961H5JPq8T/C1PZNk6fGonmVJX+3p5NZsZF9tb6c/9mlhMjFnEGBcJmcNFilN3DK44TaSqXrf302p2FEhO9UJ4OzaKzhTwNlhTwfJUtM/qyeJn1DxsxeXbUZSUIDLhTAhWFHCqBBLcgaz2luhBecYueV+Hmz+loShpB2jdjhJ9p7kFHQ1TsIh+b15A/Vsuwx/9o/8Q2PmnhxeSklAMMvl/XcnSOgO+u5ovyIQOF/KjkSm8w8hTXZmyWBHeg0uYNKtq/sqe8wWWYko8/t0Gwg9uhEM7RpMS6kGhzx9mf0dlRFsfmeIardv2Qd9kxT18zrj2XTQtwot4bVyG0bHvDThoiKJqMB6GXrB2FgFZy6I8T7HeLb+lC2fg338bhdNoAWJW16QVonzFsMoytJTMDyYLr9DZMkDu4X2gyb/xRAjaZPyefhCA/aKzG7oz3reqE1SGMxh0tRZD9Vjj7b0n8vlvjp+NDtCC5EM/oxlfCiIg8gKSn4mqajlZIbM9Bq0E5CmT1ga+k71NWYSYcFQUQ/5Ip1zTgC4IikZms7BhHl5Bn4e12mY=
node_js: stable
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
dist: trusty
