language: node_js
sudo: required
before_script:
  - npm install -g bower polymer-cli@next
  - polymer install --variants
env:
  global:
    - secure: GSYpzEW7ErHv3yWSHwk5Qh/IlcjxNaU3wAm8wcK2+yM723rYP/sXlhfmXLlKPzT8K/AEIXE8gHz3DQ2LhKipt1Zfl1IOCehHY/aaIIKQw9bdroVaOdTMW+H/tYuz4skmsP2HrDb4/S62Z7M94KCigRVS6eGS5E2752OYP11eqRKm2pfGyGxwBphZPvQ1XQFYzAcwd3ZQNp1BwJGEp1K37BGGtWtb3VIgt8CrmLn75xuzAyXl5LpnLmUffcRWgoz/UI5W8TMI2UBweOvKeEtYA1Orf7bpb2POKExg1/eWkblsMR+mrBBzRrjtiMChRNROAlZIynzVsMB4YyBh4eOsr6ioNnRbAfxXm+98Zbq7HI3UYHrz3OIV8+95Lll6bLoMO/yN0yFxeWYYe2TFsWBjYq1m7dNMq9v9vp9l5C4PgGAzbJeaJuHerPRpL+qTcES+KE4FvixOUu0CqMqVoHrBbATKndB+vchCL13dFPdAIvgV/jAMIa+3HQm093oETqwhMfi6/Mcl5aTx7pDryCGxBtMK4M0hPRnosCxILIK9kw4VJj9m4dn8nZTYqvLGRkEPqfxED+ZMArd6eGcUSSUZxTG7CImLMqfIkQKOiEiejPrb0yvsV8j48VvSoHD5DSG7Ekk4VIPRh/KzXehrEII+0hXq9N0b9tRF7dLDuZ1CGUg=
    - secure: zngZbLsf+ggYd5XjnCiZH50ToB95mR9gRjj5+0VFf9q/Sk7kbnt05LbJxaSRmZUqjGXJWPsAqPzeAB9HA0L1YcLuHOmpnjOrPxZ8KibMBw6JW3pcE/WA27hpceWkv9KHcnLX3XpiZeOyF4SngiCoz43tZaXilFsoemToTG2SFPXwsA/3Cuf7BG/wv9UIDRB4xNeeTJbGebyHv+0nNsQLBpd+EUfaT+g9M7PsCsCKdm9lBQbzbPllPVCGxxC9BSpzfV+PyLQsrsQ9h28y8Rv16zZgZj6H80TdZLOxv/qDTr6wOizEEvhBQ9OyRfhQKa4iGHx5ClkZAn44lR+PAKPQUxzq8Rc7NW1YsJfH6XGLu8ZO21Rl1PuXFit/lm8o1cKcaLAlkU5nSpLNz1xvR0sJ5cEKqg/CV7Kf7TnbiLnGJhaHsg+7JsHS+CPEE7Fow398CBQBj5DSwnmoCO3AlPd+CfrKL/wjzngJF/HTWDGYPzCw66rJlpK3JdZWtYlv83goxPrH0XTsPWyDsf9BlKfvhviLaQRkxSq0f79bBfHR8nuDyJ9JM445xUDP8ROaA8bnlKLkNGD8dQSJEJTRglK3VJBiIIhWv9/dimhsb4dkTv3g9YD13soDb2tj3rgW2iDK4/DJxuhztgqR4rLnvUxLjtcs8CtddTOMLrzM1w+dvqI=
node_js: '6'
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run polymer test
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s ''default''; fi'
dist: trusty
